import google.generativeai as genai
import os
from src.utils.correlations import correlacion_prompt
from dotenv import load_dotenv

# Cargar las variables de entorno desde el archivo .env
load_dotenv()

# Inicializa el API de Google Gemini
api_key = os.getenv("GEMINI_API_KEY")

print(f"Using API key: {api_key}")  # Debugging line to check if the API key is loaded correctly

genai.configure(api_key=api_key)

def generar_interpretacion(resumen, correlacion, n_clusters, outliers_info, relaciones_info):
    """
    Generates a data analysis interpretation using the Google Gemini API.
    """
    
    prompt = construir_prompt(resumen, correlacion, n_clusters, outliers_info, relaciones_info)

    try:
        # Definir el modelo a utilizar y la instrucción del sistema
        model = genai.GenerativeModel(
            model_name='gemini-2.5-pro',
            system_instruction="You are a professional data analyst specialized in interpreting data analysis results."
        )
        
        # Definir los parámetros de generación
        generation_config = genai.types.GenerationConfig(
            temperature=0.4,
            #max_output_tokens=4096,
        )

        # Enviar la solicitud para generar la interpretación
        response = model.generate_content(prompt, generation_config=generation_config)
        
        return response.text.strip()

    except Exception as e:
        # Manejo de errores en caso de problemas con la API
        return f"Error connecting with the Google AI API: {e}"

def construir_prompt(resumen, correlacion, n_clusters, outliers_info, relaciones_info):
    """
    Builds the prompt string to be sent to the AI. This function doesn't need changes.
    """
    texto_corr = correlacion_prompt(correlacion)

    prompt = f"""
    I have the following summary generated by an automated data analysis system:
    Technical Summary:
    {resumen}
    Featured correlations (r > 0.75):
    {texto_corr or 'No strong correlations were detected.'}
    {n_clusters} groups were detected using clustering (KMeans).
    {outliers_info or 'No significant outliers were detected.'}
    {relaciones_info or 'No strong relationships between variables were detected.'}
    
    Your task is:
    - Point out possible implications or decisions the user could make
    - Avoid unnecessary technical terms and focus on practical utility and explain the whole analysis for an understandable user
    - Explain clusters, correlations, outliers, and relationships in a way that is understandable to a non-technical user
    - Give advice on what actions the user could take based on the analysis
    - Prohibit responding in English or any other language, must be in Spanish and use a professional tone
    - Prohibit showing the code used to generate the analysis, reasoning or any other technical detail
    - Prohibit showing the summary of the analysis, only the interpretation and understandable for a non-technical user
    """.strip() 
    return prompt