import requests

# Conexion con LM Studio para usar modelo local
API_URL = "http://localhost:1234/v1/chat/completions" #endpoint de la API de LM Studio
MODEL = "meta-llama-3-8b-instruct" # Nombre del modelo

def generar_interpretacion(resumen, correlacion, n_clusters):
    prompt = construir_prompt(resumen, correlacion, n_clusters)

    try:
        payload = {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": "You are a professional data analyst specialized in interpreting data analysis results."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.4,
            "max_tokens": 750,
            "stream": False
        }

        response = requests.post(API_URL, json=payload)
        response.raise_for_status()

        data = response.json()
        return data['choices'][0]['message']['content'].strip()

    except Exception as e:
        return f"Error al conectar con LM Studio: {e}"

def construir_prompt(resumen, correlacion, n_clusters):
    texto_corr = ""
    for fila in correlacion.index:
        for col in correlacion.columns:
            r = correlacion.loc[fila, col]
            if abs(r) >= 0.75 and fila != col:
                texto_corr += f"• {fila} vs {col} → r = {r:.2f}\n"

    #Prompts en inglés son más eficientes
    prompt = f"""
    I have the following summary generated by an automated data analysis system:
    Technical Summary:
    {resumen}
    Featured correlations (r > 0.75):
    {texto_corr or 'No strong correlations were detected.'}
    {n_clusters} groups were detected using clustering (KMeans).
    Your task is:
    - Point out possible implications or decisions the user could make
    - Avoid unnecessary technical terms and focus on practical utility
    - Prohibit responding in english or any other language, must be in Spanish and use professional tone
    - Prohibit showing the code used to generate the analysis, reasoning or any other technical detail
    - Prohibit showing the summary of the analysis, only the interpretation
    """.strip()
    
    return prompt
